# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-04 08:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EtcdCluster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('cname', models.CharField(default='', max_length=100)),
                ('numofnodes', models.IntegerField()),
                ('nodesname', models.CharField(default='', max_length=100)),
                ('ips', models.CharField(max_length=100)),
                ('peerport', models.CharField(default='', max_length=100)),
                ('clientport', models.CharField(default='', max_length=100)),
                ('isdeployed', models.BooleanField(default=True)),
            ],
        ),
    ]
